version: "3.7"

services:

  web:
    image: nginx:1.17
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/myapp
      - ./site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - php

  php:
    image: php:7.4-fpm
    volumes:
      - ./src:/var/www/myapp
      - ./php.ini:/usr/local/etc/php/php.ini

  phpunit:
    image: php:7.4-cli
    volumes:
      - ./src:/var/www/myapp
      - ./tests:/var/www/tests
      - ./php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/myapp
    entrypoint: vendor/bin/phpunit

  composer:
    image: composer:1.9
    volumes:
      - ./src:/app
